### ISSUE TITLE
ERROR: Specified cast is not valid

### ISSUE THREAD

**Issue by jaganz** [flcdrg/chocolatey-ssms#3]
**Installation:**

```
C:\WINDOWS\system32>choco install sql-server-management-studio -y
Chocolatey v0.10.11
Installing the following packages:
sql-server-management-studio
By installing you accept licenses for the packages.
Progress: Downloading sql-server-management-studio 14.0.17277.0... 100%

sql-server-management-studio v14.0.17277.0 [Approved]
sql-server-management-studio package files install completed. Performing other installation steps.
ERROR: Specified cast is not valid.
The install of sql-server-management-studio was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\sql-server-management-studio\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - sql-server-management-studio (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\sql-server-management-studio\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Logs:** attached
[chocolatey.log](https://github.com/flcdrg/chocolatey-ssms/files/2331534/chocolatey.log)

**Comment by flcdrg** [comment]
Thanks for the info and log. I wonder if it's related to the restart detection that I added recently? I'll do some testing to see if I can reproduce the problem.

**Comment by jaganz** [comment]
I have found something similar in this issue: https://github.com/dtgm/chocolatey-packages/issues/167 . Hope this can help you

**Comment by flcdrg** [comment]
Also realised I need to update the packageSourceUrl to point to the new Git repository!

**Comment by flcdrg** [comment]
@jaganz if you run the PowerShell script mentioned in that related issue, what output do you get?

**Comment by jaganz** [comment]
```
WARNING: Found bad key:
Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-base-
8.2.0.0.201609300101
```

**Comment by jaganz** [comment]
The workaround seems to be

> As you may have noticed, this bug affects many packages on chocolatey.org and most all install packages I maintain. This will be slowly snuffed out as old packages get updated. For now, the workaround is to remove the offending application, or, if you need the offending software installed, fix the bad registry key.

i'll try and give u feedback

**Comment by flcdrg** [comment]
Sounds good. Looks like that key is related to Netbeans (according to Google)

**Comment by jaganz** [comment]
Afeter deleted the bad registry entry (attached, I think that are the parameters for netbeans uninstaller) everythings works fine. thanks! 

> C:\WINDOWS\system32>choco install sql-server-management-studio -y
Chocolatey v0.10.11
Installing the following packages:
sql-server-management-studio
By installing you accept licenses for the packages.
Progress: Downloading sql-server-management-studio 14.0.17277.0... 100%

sql-server-management-studio v14.0.17277.0 [Approved]
sql-server-management-studio package files install completed. Performing other installation steps.
Downloading SQL Server Management Studio
  from 'https://download.microsoft.com/download/0/5/B/05B2AF8F-906F-4C57-A58E-5780F64F9D62/SSMS-Setup-ENU.exe'
Progress: 100% - Completed download of C:\Users\ilari\AppData\Local\Temp\chocolatey\sql-server-management-studio\14.0.17277.0\SSMS-Setup-ENU.exe (806.28 MB).
Download of SSMS-Setup-ENU.exe (806.28 MB) completed.
Hashes match.
Installing SQL Server Management Studio...
SQL Server Management Studio has been installed.
  sql-server-management-studio may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of sql-server-management-studio was successful.
  Software installed as 'EXE', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[nbi-nb-base-8.2.0.0.201609300101.reg.zip](https://github.com/flcdrg/chocolatey-ssms/files/2332256/nbi-nb-base-8.2.0.0.201609300101.reg.zip)

**Comment by jaganz** [comment]
Afeter deleted the bad registry entry (attached, I think that are the parameters for netbeans uninstaller) everythings works fine. thanks! 

> C:\WINDOWS\system32>choco install sql-server-management-studio -y
Chocolatey v0.10.11
Installing the following packages:
sql-server-management-studio
By installing you accept licenses for the packages.
Progress: Downloading sql-server-management-studio 14.0.17277.0... 100%
sql-server-management-studio v14.0.17277.0 [Approved]
sql-server-management-studio package files install completed. Performing other installation steps.
Downloading SQL Server Management Studio
  from 'https://download.microsoft.com/download/0/5/B/05B2AF8F-906F-4C57-A58E-5780F64F9D62/SSMS-Setup-ENU.exe'
Progress: 100% - Completed download of C:\Users\ilari\AppData\Local\Temp\chocolatey\sql-server-management-studio\14.0.17277.0\SSMS-Setup-ENU.exe (806.28 MB).
Download of SSMS-Setup-ENU.exe (806.28 MB) completed.
Hashes match.
Installing SQL Server Management Studio...
SQL Server Management Studio has been installed.
  sql-server-management-studio may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of sql-server-management-studio was successful.
  Software installed as 'EXE', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Registry zipped [nbi-nb-base-8.2.0.0.201609300101.reg.zip](https://github.com/flcdrg/chocolatey-ssms/files/2332256/nbi-nb-base-8.2.0.0.201609300101.reg.zip)

**Comment by flcdrg** [comment]
No worries!

**Comment by flcdrg** [comment]
This issue was moved to flcdrg/au-packages#37
